server:
  port: 8081  # Puerto para el microservicio ms-auth-service

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/authdb
    username: postgres
    password: 123456
  cloud:
    config:
      uri: http://localhost:8888
    consul:
      discovery:
        service-name: ms-auth-service
