server:
  port: 8081  # Puerto para el microservicio ms-auth-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
