server:
  port: 8082  # Puerto para el microservicio ms-student-service

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/studentdb
    username: postgres
    password: 123456
  cloud:
    config:
      uri: http://localhost:8888
    consul:
      discovery:
        service-name: ms-student-service