server:
  port: 8082

spring:
  application:
    name: ms-student-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/msstudentservice
    username: postgres
    password: password

  cloud:
    config:
      import: "optional:configserver:http://localhost:8888"

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/auth/realms/your-realm
